const dataConfigs = {
  song: {
    id: 'id',
    title: ['title', 'name'],
    subtitle: ['subtitle', 'artists', 'language', 'type'],
    image: ['image.2.link', 'image.0.link', 'artwork', 'atw', 'atwj'],
    artists: 'artists',
    duration: 'duration',
    token: ['token', 'id'],
  },
  album: {
    id: 'id',
    title: ['title', 'name'],
    artists: 'artists',
    image: ['image.2.link', 'image.0.link', 'artwork', 'atw', 'atwj'],
    subtitle: ['editorFirstName', 'subTitle', 'type', 'subtitle', 'artists', 'language'],
    year: 'releaseYear',
    editor: 'editorFirstName',
    duration: 'duration',
    token: ['token', 'id'],
  },
  playlist: {
    id: 'id',
    title: ['title', 'name'],
    subtitle: ['subTitle', 'subtitle', 'editorFirstName', 'followers', 'language'],
    image: ['image.2.link', 'image.0.link', 'artwork', 'atw', 'atwj'],
    description: 'description',
    year: 'year',
    trackCount: 'listCount',
    token: ['token', 'id'],
  },
  albumHero: {
    id: 'id',
    token: ['token', 'id'],
    title: 'title',
    description: 'description',
    year: 'year',
    trackCount: 'listCount',
    copyright: 'copyright',
  },
  audio: {
    id: 'id',
    title: 'title',
    subtitle: 'subtitle',
    image: 'image.1.link',
    duration: 'duration',
    artists: 'artists',
    palette: 'palette',
  },
  radio: {
    id: 'id',
    language: 'language',
    name: 'name',
    title: ['title', 'name'],
    image: ['image.2.link', 'image.0.link', 'artwork', 'atw', 'atwj'],
    subtitle: ['subtitle', 'description'],
    token: ['token', 'perma_url', 'id'],
  },
  radio_station: {
    id: ['id', 'stationid'],
    language: 'language',
    name: 'name',
    title: ['title', 'name'],
    image: ['image.2.link', 'image.0.link', 'artwork', 'atw', 'atwj'],
    subtitle: ['subtitle', 'description'],
    token: ['token', 'perma_url', 'id'],
  },
  channel: {
    id: 'id',
    title: ['title', 'name'],
    image: ['image.2.link', 'image.0.link', 'artwork', 'atw', 'atwj'],
    subtitle: ['subtitle', 'description'],
    token: ['token', 'perma_url', 'id'],
  },
  artist: {
    id: ['id', 'artistId'],
    title: ['title', 'name'],
    image: ['image.2.link', 'image.0.link', 'artwork', 'atw', 'atwj'],
    subtitle: ['subtitle', 'type'],
    token: ['token', 'perma_url', 'id'],
  },
  occasion: {
    id: 'id',
    title: ['title', 'name'],
    image: ['image.2.link', 'image.0.link', 'artwork', 'atw', 'atwj'],
    subtitle: ['type'],
    token: ['url', 'slug', 'id'],
  },
} as const;

export { dataConfigs };
